#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=common.sh
source "$SCRIPT_DIR/common.sh"

tmp_root="$(new_tmp_root memory)"
workspace="$tmp_root/workspace"
mkdir -p "$workspace"

printf 'Smoke Project\nMemory smoke test\ntestuser\nEnglish\nassistant\nconclusion first\ninspect then edit\npromote confirmed prefs only\n' \
  | "$ROOT_DIR/scripts/memory/interview.sh" --workspace "$workspace" --platform codex >/tmp/cccg-memory.out 2>&1

assert_file_exists "$workspace/.assistant/SYSTEM.md"
assert_file_exists "$workspace/.assistant/USER.md"
assert_file_exists "$workspace/.assistant/STYLE.md"
assert_file_exists "$workspace/.assistant/runtime/active-task.md"
assert_file_exists "$workspace/.assistant/runtime/interrupted-tasks.md"
assert_file_exists "$workspace/.assistant/runtime/last-session.md"
assert_file_exists "$workspace/.assistant/runtime/resume-checkpoint-template.md"
assert_contains "$workspace/.assistant/SYSTEM.md" "Project: Smoke Project"
assert_contains "$workspace/.assistant/USER.md" "Preferred name: testuser"
assert_contains "$workspace/.assistant/WORKFLOW.md" "Preferred workflow: inspect then edit"
assert_contains "$workspace/.assistant/WORKFLOW.md" "Quick recall protocol:"
assert_contains "$workspace/.assistant/WORKFLOW.md" "Quick recall trigger phrases include:"
assert_contains "$workspace/.assistant/WORKFLOW.md" "Quick recall source priority: active-task.md first"
assert_contains "$workspace/.assistant/WORKFLOW.md" "Quick recall speed rule:"
assert_contains "$workspace/.assistant/WORKFLOW.md" "Quick recall language rule:"
assert_contains "$workspace/.assistant/WORKFLOW.md" "the first recovery reply should use exactly three sections in order"
assert_contains "$workspace/.assistant/WORKFLOW.md" "Quick recall readability rule:"
assert_contains "$workspace/.assistant/WORKFLOW.md" "main task section must contain exactly three lines"
assert_contains "$workspace/.assistant/WORKFLOW.md" "if other interrupted tasks exist, list them in priority order, and for each task use the same structure: task: ..., priority: ..., progress: ..., next step: ...."
assert_contains "$workspace/.assistant/WORKFLOW.md" "Quick recall hard rule:"
assert_contains "$workspace/.assistant/WORKFLOW.md" "Recovery follow-up rule:"
assert_contains "$workspace/.assistant/WORKFLOW.md" "Recovery choice rule:"
assert_contains "$workspace/.assistant/WORKFLOW.md" "Recovery language rule:"
assert_contains "$workspace/.assistant/WORKFLOW.md" "Recovery formatting hard rule:"
assert_contains "$workspace/.assistant/runtime/active-task.md" "Task: none"
assert_contains "$workspace/.assistant/runtime/interrupted-tasks.md" "| Priority | Paused At | Task | Status | Next Step |"
assert_contains "$workspace/.assistant/runtime/interrupted-tasks.md" "Preferred recovery options:"
assert_contains "$workspace/.assistant/runtime/interrupted-tasks.md" "1. 继续当前主任务"
assert_contains "$workspace/.assistant/runtime/last-session.md" "Task: Initial workspace memory bootstrap"
assert_contains "$workspace/.assistant/runtime/last-session.md" "Next step: Continue any pending IM / MCP / skills setup from unified bootstrap state"
assert_contains "$workspace/.assistant/runtime/resume-checkpoint-template.md" "Paused at:"
assert_contains "$workspace/.assistant/runtime/resume-checkpoint-template.md" "Priority:"
assert_contains "$workspace/.assistant/runtime/resume-checkpoint-template.md" "Priority note: active-task.md should be checked before named checkpoints during resume."
assert_contains "$workspace/.assistant/runtime/resume-checkpoint-template.md" "Format hard rule:"
assert_contains "$workspace/.assistant/runtime/resume-checkpoint-template.md" "Follow-up section:"
assert_contains "$workspace/.assistant/runtime/resume-checkpoint-template.md" "Choice section:"
assert_contains "$workspace/.assistant/runtime/resume-checkpoint-template.md" "A. Current main task"
assert_contains "$workspace/.assistant/runtime/resume-checkpoint-template.md" "B. Other interrupted tasks"
assert_contains "$workspace/.assistant/runtime/resume-checkpoint-template.md" "C. Recovery options"
assert_contains "$workspace/.assistant/runtime/resume-checkpoint-template.md" "priority: P2"
assert_contains "$workspace/.assistant/runtime/resume-checkpoint-template.md" "Resume answer format:"

echo "PASS: memory interview"
